name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0'
    - name: "Run swift package"
      run: |
        swift package resolve
    - name: "Run swift build"
      run: swift build --verbose
    - name: "Run swift test"
      run: swift test --verbose
